name: "infra preview & deploy"

on:
  push:
    branches:
      - main
    paths:
      - 10_infra/**
      - .github/workflows/**
    workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  TF_VERSION: 1.2.8
  AWS_REGION: ap-northeast-1
  TF_PROJECT: dev-app
  TF_ENVIRONMENT: dev

defaults:
  run:
    shell: bash
    working-directory: "10_infra/"

jobs:
  preview:
    name: "Preview"
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository # Runner(実行環境にリポジトリからデータをダウンロードして持ってくる)
        uses: actions/checkout@v3
      - name: setup terraform # terrafrom cliの初期化アクション
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }} #Terraformのバージョン指定
      - name: Terraform format # formatが適用できているのか確認
        run:
          terraform fmt -check # -check: 終了ステータスとして問題なければ０,あればそれ以外を返す
      - name: Configure AWS credential # terraform init等でs3へのバケットアクセスあるので事前にクレデンシャル設定必要
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Terraform init
        run:
          terraform init -no-color
      - name: Terraform validate
        run:
          terraform validate -no-color
      - name: Terraform plan # 現在のDeploy環境との差分チェック
        run:
          terraform plan 
            -var 'project=${{ env.TF_PROJECT }}' \
            -var 'environment=${{ env.TF_ENVIRONMENT }}' \
            -var 'username=${{ secrets.MYSQL_PASSWORD }}' \
            -var 'password=${{ secrets.MYSQL_USERNAME }}'\
